// /////////////////////////////////
// ///	  Config Class
// ///		Triage
// ///	  by Mike LaGrange
// ////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections;
using UnityEngine;

public static class GameConfig
{
	public static string[] ValidGameEvents = new string[] {
											"NewTurnStart",s
											"ActionPlayed",
											"CharacterCollected",
											"ActionRecharged",
											"ActionRoundStart",
											"CollectionRoundStart",
											"PlayerInformationUpdate",
											"CharacterQueueChange",
											"EndOfTurn"
										};

	public static string[] GameEventOrder = new string[] {
														"NewTurnStart",
														"ActionRoundStart",
														"CollectionRoundStart",
														"EndofTurn"
													};
}

